#pragma once


/**
 * @brief Aerodynamic coefficients for airfoil performance
 */
struct AirfoilAeroCoefficients {
    /**
     * @brief Lift coefficient (Cl)
     *
     * Represents the lift generated by the airfoil at a given angle of attack.
	 */
    double cl = 0.0;  // Lift coefficient

    /**
     * @brief Drag coefficient (Cd)
     *
	 * Represents the drag force acting on the airfoil at a given angle of attack.
	 */
    double cd = 0.0;  // Drag coefficient

    /**
     * @brief Moment coefficient (Cm)
	 */
    double cm = 0.0;  // Moment coefficient

    /**
     * @brief Default constructor
	 */
    AirfoilAeroCoefficients() = default;
    
    /**
	 * @brief Parameterized constructor for aerodynamic coefficients
	 * @param lift
     * @param drag
     * @param moment
     */
    AirfoilAeroCoefficients(double lift, double drag, double moment)
        : cl(lift), cd(drag), cm(moment) {
    }
};